apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 39.2.1
    helm:
      skipCrds: true
      values: |
        alertmanager:
          config:
            route:
              group_by: ['namespace']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: default
              routes:
              - receiver: default
                matchers:
                  - alertname =~ "InfoInhibitor|Watchdog"
            receivers:
              - name: default
                pagerduty_configs:
                - service_key: {{ .Values.observability.pdkey }}
        prometheus:
          prometheusSpec:
            retention: {{ .Values.observability.retention }}
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: {{ .Values.storageClass }}
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: {{ .Values.observability.storageSize }}
        grafana:
          service:
            type: LoadBalancer
          additionalDataSources:
            - name: loki
              type: loki
              url: http://loki.observability.svc.cluster.local:3100
            - name: tempo
              type: tempo
              url: http://tempo.observability.svc.cluster.local:3100


    chart: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
